<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dk.rmgroup.keycloak</groupId>
    <artifactId>fk-api-user-federation</artifactId>
    <version>26.6.3-3</version>

    <name>fk-api-user-federation</name>
    <url>https://github.com/RiskManagementGroup/keycloak-fk-api-user-federation</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <keycloak.version>26.6.3</keycloak.version>
        <cxf.version>4.2.2</cxf.version>
        <resources>${basedir}/src/main/resources</resources>
        <!-- TODO: Add WSDL files here-->
        <wsdl.Organisation>wsdl/Organisation.wsdl</wsdl.Organisation>
        <wsdl.Virksomhed>wsdl/Virksomhed.wsdl</wsdl.Virksomhed>
        <wsdl.Bruger>wsdl/Bruger.wsdl</wsdl.Bruger>
        <wsdl.Adresse>wsdl/Adresse.wsdl</wsdl.Adresse>
        <wsdl.Person>wsdl/Person.wsdl</wsdl.Person>
        <wsdl.OrganisationEnhed>wsdl/OrganisationEnhed.wsdl</wsdl.OrganisationEnhed>
        <wsdl.OrganisationSystem>wsdl/OrganisationSystem.wsdl</wsdl.OrganisationSystem>
        <wsdl.OrganisationFunktion>wsdl/OrganisationFunktion.wsdl</wsdl.OrganisationFunktion>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-parent</artifactId>
                <version>${keycloak.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20260522</version>
        </dependency>

        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-server-spi</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-server-spi-private</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-services</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>jboss-logging</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-frontend-jaxws</artifactId>
            <version>${cxf.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.glassfish.jaxb</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-ws-security</artifactId>
            <version>${cxf.version}</version>

            <exclusions>
                <exclusion>
                    <groupId>stax</groupId>
                    <artifactId>stax-api</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>javax.xml.stream</groupId>
                    <artifactId>stax-api</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.glassfish.jaxb</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>

        </dependency>

        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-core</artifactId>
            <version>${cxf.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-transports-http</artifactId>
            <version>${cxf.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.santuario</groupId>
            <artifactId>xmlsec</artifactId>
            <version>4.0.4</version>
        </dependency>

        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-features-logging</artifactId>
            <version>${cxf.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>6.2.8</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>6.2.8</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>6.2.8</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
            <version>6.2.8</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-expression</artifactId>
            <version>6.2.8</version>
        </dependency>

    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>keys/**</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
            <!-- Generates classes from WSDL files -->
            <plugin>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-codegen-plugin</artifactId>
                <version>${cxf.version}</version>
                <executions>
                    <execution>
                        <id>generate-sources</id>
                        <phase>generate-sources</phase>
                        <configuration>
                            <sourceRoot>${project.build.directory}/generated-sources/cxf</sourceRoot>
                            <!-- TODO: Add WSDL files here-->
                            <wsdlOptions>
                                <wsdlOption>
                                    <wsdl>${resources}/${wsdl.Organisation}</wsdl>
                                    <wsdlLocation>classpath:${wsdl.Organisation}</wsdlLocation>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${resources}/${wsdl.Virksomhed}</wsdl>
                                    <wsdlLocation>classpath:${wsdl.Virksomhed}</wsdlLocation>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${resources}/${wsdl.Bruger}</wsdl>
                                    <wsdlLocation>classpath:${wsdl.Bruger}</wsdlLocation>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${resources}/${wsdl.Adresse}</wsdl>
                                    <wsdlLocation>classpath:${wsdl.Adresse}</wsdlLocation>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${resources}/${wsdl.Person}</wsdl>
                                    <wsdlLocation>classpath:${wsdl.Person}</wsdlLocation>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${resources}/${wsdl.OrganisationEnhed}</wsdl>
                                    <wsdlLocation>classpath:${wsdl.OrganisationEnhed}</wsdlLocation>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${resources}/${wsdl.OrganisationSystem}</wsdl>
                                    <wsdlLocation>classpath:${wsdl.OrganisationSystem}</wsdlLocation>
                                </wsdlOption>
                                <wsdlOption>
                                    <wsdl>${resources}/${wsdl.OrganisationFunktion}</wsdl>
                                    <wsdlLocation>classpath:${wsdl.OrganisationFunktion}</wsdlLocation>
                                </wsdlOption>
                            </wsdlOptions>
                        </configuration>
                        <goals>
                            <goal>wsdl2java</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>

                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring.handlers</resource>
                                </transformer>

                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring.schemas</resource>
                                </transformer>

                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring.tooling</resource>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/cxf/bus-extensions.txt</resource>
                                </transformer>

                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/cxf/cxf-extension-jaxws.xml</resource>
                                </transformer>

                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/cxf/cxf-extension-http.xml</resource>
                                </transformer>

                            </transformers>
                            <artifactSet>
                                <excludes>
                                    <exclude>org.keycloak:*</exclude>
                                    <exclude>io.quarkus:*</exclude>
                                    <exclude>org.glassfish.jaxb:*</exclude>
                                    <exclude>jakarta:*</exclude>
                                </excludes>
                            </artifactSet>
                            <relocations>
                                <relocation>
                                    <pattern>org.objectweb.asm</pattern>
                                    <shadedPattern>dk.rmgroup.shaded.asm</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.json</pattern>
                                    <shadedPattern>dk.rmgroup.fk.shaded.org.json</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
