
#region Variables which MUST BE MODIFIED before running the code examples

    # Keys and Truststore - Must be changed
    # Insert keystore file path
    org.apache.wss4j.crypto.merlin.keystore.file=keys/sts_wf_keystore_29.jks
    # Insert keystore password
    org.apache.wss4j.crypto.merlin.keystore.password=

    # Insert truststore file path
    org.apache.wss4j.crypto.merlin.truststore.file=opt/keycloak/conf/truststores/fk-truststore.production.p12
    #keys/truststore.production.jks
    # Insert truststore password
    org.apache.wss4j.crypto.merlin.truststore.password=

    # CVR and name of the municipality (myndighed) that will be used to test
    # Insert CVR for test authority - e.g. 11111111
    #myndighedCvr=29189676
    #18957981
    #29189625
    #11111111

#endregion

#region Variables for endpoints - CAN be modified

    # Endpoint URLs
    # SagdokumentIndeks
    sagdokumentIndeksEndpointUrl=https://sagsogdokumentindeks.stoettesystemerne.dk/sagdokumentindeks/6
    # Klassifikation
    klassifikationEndpointUrl=https://klassifikation.stoettesystemerne.dk/klasse/7
    # Organisation
    organisationEndpointUrl=https://organisation.stoettesystemerne.dk/organisation/organisation/6
    # Virksomhed
    virksomhedEndpointUrl=https://organisation.stoettesystemerne.dk/organisation/virksomhed/6
    # Bruger
    brugerEndpointUrl=https://organisation.stoettesystemerne.dk/organisation/bruger/6
    # Adresse
    adresseEndpointUrl=https://organisation.stoettesystemerne.dk/organisation/adresse/6
    # Person
    personEndpointUrl=https://organisation.stoettesystemerne.dk/organisation/person/6
    # OrganisationEnhed
    organisationEnhedEndpointUrl=https://organisation.stoettesystemerne.dk/organisation/organisationenhed/6
    # OrganisationSystem
    organisationSystemEndpointUrl=https://organisation.stoettesystemerne.dk/organisation/organisationsystem/6
    # OrganisationFunktion
    organisationFunktionEndpointUrl=https://organisation.stoettesystemerne.dk/organisation/organisationfunktion/6

#endregion
